version: '3.7'
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    tty: true
    stop_signal: SIGINT
    environment:
      # For security improvements, you should do this with a more suitable method,
      # like Docker Secretes
      - SESSION_SECRET=${CONF_ZWJS_SESSION_SECRET}
    networks:
      - homeassistant
    devices:
      - ${HW_USB_RF_ZWAVE}:/dev/zwave
    volumes:
      - ~/git/ha/zwavejs-config:/usr/src/app/store
    ports:
    # !Unsecured! 
    # - 3000:3000 # WS <-> HA
      - 127.0.0.1:8091:8091 # WebUI
    expose:
      - 3000
    security_opt:
      - seccomp:unconfined
volumes:
  zwave-config:
    name: zwave-config
