version: '3.7'
services:
  homeassistant:
    restart: unless-stopped
    container_name: homeassistant
    image: "ghcr.io/home-assistant/raspberrypi3-homeassistant:${DOCKER_IMAGE_HA_VER}"

  deconz:
    restart: unless-stopped
    container_name: deconz
    image: deconzcommunity/deconz:${DOCKER_IMAGE_DECONZ_VER}

  zwavejs2mqtt:
    restart: unless-stopped
    container_name: zwavejs2mqtt
    image: zwavejs/zwave-js-ui:${DOCKER_IMAGE_ZWJS_UI_VER}

  esphome:
    restart: unless-stopped
    container_name: esphome
    image: "ghcr.io/esphome/esphome:${DOCKER_IMAGE_ESPHOME_VER}"

networks:
  homeassistant:
