version: '3.7'
services:
  homeassistant:
    container_name: homeassistant
    volumes:
      - ~/git/ha/ha-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - DISABLE_JEMALLOC=true
