version: '3.7'
services:
  homeassistant:
    container_name: homeassistant
    volumes:
      - ~/git/ha/ha-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    #network_mode: host #Security fix
    networks:
      - homeassistant
    ports:
      - "8123:8123"
    environment:
      - DISABLE_JEMALLOC=true
